### ISSUE TITLE
Simplify error message

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#110]
It's nice that we have error messages in the showcase - but what does this mean?

https://travis-ci.com/github/c4dt/showcase/builds/199935262

Is it possible to simplify those messages with something like:
```
Checking project file AAA - OK
Checking project file DCL - Error in project `FeGAN`: field `something` is `something`
```
?

**Comment by cgrigis** [comment]
> It's nice that we have error messages in the showcase - but what does this mean?

The relevant information in the error trace is to be found here (the lines starting with E):
```
E                   ruamel.yaml.scanner.ScannerError: mapping values are not allowed here
E                     in "/home/travis/build/c4dt/showcase/data/DCL/projects.yaml", line 213, column 27:
E                                     title: FeGAN: Scaling Distributed GANs
E                                                 ^ (line: 213)
```

I highly recommend using `make test` on the command line, which makes the above more obvious by coloring it in red. :)

YAML's peculiarities don't always make the error messages obvious, but that is YAML...

> Is it possible to simplify those messages with something like:
> 
> ```
> Checking project file AAA - OK
> Checking project file DCL - Error in project `FeGAN`: field `something` is `something`
> ```
> 
> ?

What do you mean by "field `something` is `something`?

I will check if there are some `precommit` filters that help.

**Comment by ineiti** [comment]
The goal is that it's usable by the MSU (Most Stupid User... Me...) - I think you already told me about the lines with an `E`, but of course I forgot.

In this case it would be:
```
Checking project file DCL - Error in project `FeGAN`: field `title` is `mapping values are not allowed here`
```

But I think that a `egrep "/^E /"` on the output would already be great!

**Comment by cgrigis** [comment]
Trying to parse the error messages out of a library seems very brittle to me.

I added a pre-commit hook in #201.
