### ISSUE TITLE
Ordering of entries

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#121]
New idea for ordering of the entries: from the most recent worked on (code::date_last_commit or date_added)

**Comment by cgrigis** [comment]
Should this become the default sorting? (as a reminder, the current default sorting is _Maturity_ descending + _Professor name_ ascending + _Project name_ ascending).

**Comment by ineiti** [comment]
Good point. What about `Maturity descending`, then `code::date_last_commit || date_added`, then `Professor name`, then `Project name`?

**Comment by cgrigis** [comment]
Sounds good.
This affects only the sorting, and the "project activity" (which gives the green background in the list view, and the `active` status in the project view) remains based on the `date_last_commit`?

**Comment by ineiti** [comment]
yes, only sorting. The project activity is very good as is. Even if I have to adjust a bit the "active project delay" due to the showcase not being updated frequent enough...

**Comment by cgrigis** [comment]
Should be done. I will let you close this if good.

**Comment by ineiti** [comment]
Cool, looks good! Now the most up-to-date projects are on top, this is very nice!
