### ISSUE TITLE
Add text for incubator work

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#122]
We need a way to indicate what work the C4DT did for incubator and market projects. I propose we add a `c4dt_desc` field in the yaml files for this.

**Comment by cgrigis** [comment]
Where should this be displayed?

Possibilities:
* In the project-specific page of the showcase, in the top section, after "Factory involvement"
* In the project-specific page of the showcase, in the second section, after the "Layman description"
* In the incubator and demo pages, after the "Layman description"

**Comment by ineiti** [comment]
More options:
4) In the project-specific page of the showcase, as alternative text to "Factory involvement"
5) In the incubator and demo pages, after the "Layman description", without any special labelling

**Comment by cgrigis** [comment]
Are those options, or what you would like? :)

**Comment by ineiti** [comment]
What I like, please?

**Comment by cgrigis** [comment]
Done. I named the field `c4dt_work`, and it is mandatory if the project has `in_incubator: true`.
I filled in the field for the non-GAEN lib project as a test, and left the other currently empty. If the field is empty, the same text is displayed as before in the project details page.
