### ISSUE TITLE
Add c4dt contact to /projects list

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#123]
when a project only has a `c4dt_contact`, it will not show up in the contact-column of the `/projects/labname` list.

Wanted: the `contact` column of the `/project/labname` should be `contact || c4dt_contact`.

**Comment by cgrigis** [comment]
Currently, `c4dt_contact` only exists for projects in the incubator, so some projects would still show no contact (e.g. `cola` in the MLO).

Possibilities:
* Require `c4dt_contact` for all projects.
* Use a default C4DT contact when the list of contacts is empty and there is no `c4dt_contact`.
* Use the lab Prof as contact when the list of contacts is empty and there is no `c4dt_contact`.
* Inquire with the Profs to find missing contacts.

**Comment by ineiti** [comment]
1) I would not put a C4DT contact for non-incubator projects, that looks like a lot of work ;)
2) In fact the professor's name in the first entry of the project details is an email link to the professor, so this is kind of already done
3) That's what I did for the last couple of weeks ;)
4) Like 1), I would not do it. Only projects >= incubator should have a C4DT contact

**Comment by cgrigis** [comment]
1. I meant to add a default hard-coded contact, so it's not a lot of work.
2. Yes, but it does not (currently) show up in the contact column of the project list.
3. Indeed. So eventually the problem will go away ;)
4. OK.

**Comment by ineiti** [comment]
2. is best then.

**Comment by cgrigis** [comment]
Done.
