### ISSUE TITLE
Links to labs and project lists of labs

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#128]
I often want to go from the showcase/projects page to the lab-page of the project. But if I click on the professor's name, it opens an email to him/her.

Would it be difficult to do the following changes?
- showcase/projects - replace the `Professor` column with a `Professor / Lab` column (e.g., `Carmela Troncoso / SPRING`), and link to showcase/projects/lab instead of the official lab page
- showcase/labs - rename the `Lab` column with `Lab Projects`, and `Full Name` with `Official Lab Page`
- showcase/projects/LAB - rename the `Professor` with `Professor / Lab`, but keep the link

It would make it clearer to me. What do you think, @cgrigis , @tharvik ?

**Comment by cgrigis** [comment]
Those things have been changed back and forth several times, so I don't really have an opinion. :)

> I often want to go from the showcase/projects page to the lab-page of the project. But if I click on the professor's name, it opens an email to him/her.

I'm a bit confused: on the `https://showcase.c4dt.org/projects/` (or `https://showcase.c4dt.org/projects/<LAB>` which is the same, just filtered for the given lab), the link in the `Professor` column points to the lab home page (on the EPFL site), the link in the `Lab` column (hidden by default) points to `https://showcase.c4dt.org/projects/<LAB>`, and the links in the `Contact` column point to the contact email.

>    showcase/projects - replace the `Professor` column with a `Professor / Lab` column (e.g., `Carmela Troncoso / SPRING`), and link to showcase/projects/lab instead of the email

So you mean to merge the `Professor` and `Lab` columns?

>     showcase/labs - rename the `Lab` column with `Lab Projects`, and `Full Name` with `Official Lab Page`

OK

>     * showcase/projects/LAB - rename the `Professor` with `Professor / Lab`, but keep the link

Hmm OK so it's no longer a simple filter.

Perhaps we should make the `Lab` column, currently hidden by default, visible by default, and rename the columns?

**Comment by cgrigis** [comment]
Changes done according to our discussion (see #130 for details).
Let me know if you need other changes.

**Comment by ineiti** [comment]
OK, looks great - now I see that the title just above the table indeed is a very bad idea, sorry. I propose to do the following:

- Move the title to the top again, with the link
- remove the first sentence of the description

Probably the text should be in fact an introduction to the lab itself. That's for another issue, though.

**Comment by cgrigis** [comment]
Done in #132.

**Comment by ineiti** [comment]
Cool - looks better.
