### ISSUE TITLE
Change indication of missing Maturity Evaluation

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#134]
For one of the projects w/o a Maturity Evaluation, one of the professors asked why it's so low. I propose to do the following:

if there is no Maturity Evaluation, replace the gray moon with a `N/A` and a hover-text, or link (whichever is easier) to a short explanation that we're happy to create a maturity evaluation of the project upon request.

**Comment by cgrigis** [comment]
Done in #135.
