### ISSUE TITLE
Update showcase lab data

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#136]
next up:

done:
- [x] 2021-02-08 - @tharvik - DCL
- [x] 2021-02-15 - @cgrigis - DEDIS
- [x] 2021-02-22 - @ineiti - DSLAB
- [x] 2021-03-01 - @tharvik - HexHive
- [x] 2021-03-08 - @cgrigis - INDY
- [x] 2021-03-15 - @ineiti - IVRL
- [x] 2021-03-22 - @tharvik - LARA
- [x] 2021-03-29 - @cgrigis - LCA2
- [x] 2021-04-12 - @ineiti - LDS
- [x] 2021-04-19 - @tharvik - LSIR
- [x] 2021-04-26 - @cgrigis - LTS4
- [x] 2021-05-10 - @tharvik - MMSPG
- [x] 2021-05-17 - @cgrigis - NAL
- [x] 2021-05-03 - @ineiti - MLO
- [x] 2021-05-24 - @ineiti - PARSA
- [x] 2021-05-31 - @tharvik - SLAB -> SalatheLab
- [x] 2021-06-07 - @cgrigis - SPRING

**Comment by tharvik** [comment]
Do it @tharvik !

**Comment by tharvik** [comment]
It's done, yeeah! :1st_place_medal:
