### ISSUE TITLE
test-incubator

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#149]
- link to lab needs to be smaller:
  - [x] full name of the lab in same font as rest
  - [x] abbreviation with link
- [x] MedCo image smaller
- [x] Breadcrumbs more visible, e.g., dark background and keep always on top (display, block, float, whatever)
- [ ] dark mode:
```css
@media (prefers-color-scheme: dark) {
  /* Dark theme styles go here */
}
 
@media (prefers-color-scheme: light) {
  /* Light theme styles go here */
}
```

**Comment by cgrigis** [comment]
Dark mode extracted as #156.
