### ISSUE TITLE
Re-arrange subdomains for factory work

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#159]
To stop the number of subdomains used increasing, we propose the following system:

- `factory.c4dt.org` is the main domain for our software-work. Visiting this domain redirects to https://www.c4dt.org/factory/software/ which gives an overview of the showcase, the incubator, and the market with entry-points to the list of these three activities
- the different activities of the factory can then be found in the path of the url:
- `/showcase` and all its subpaths are rewritten (which does not change the URL in the client's browser) by apache to point to the current showcase.c4dt.org and its subpaths
- `/incubator` alone points to all projects that are in the incubator. The following paths are available:
  - `/presentations` alone points to all presentations available. Each presentation has its own path in here, e.g., `/incubator/presentations/spindle` shows the spindle presentation
  - `/demos` alone points to all available demos. Each demo has its own path, like `/presentations`
  - `/hands-on` alone points to all available hands-on workshops. Each workshop has a small description. They are not referenced specifically, so `/hands-on/drynx` does not exist
  - `/pilots` alone points to all available pilots. They are the only ones having their subdomain. Currently this is only `login.c4dt.org`
- `/market` alone points to all projects in the market. Currently this is only `OmniLedger`. Each project in the market is available in a path, e.g., `/market/omniledger`

**Comment by cgrigis** [comment]
>  `/incubator` alone points to all projects that are in the incubator. The following paths are available:
>       
>    `/presentations` alone points to all presentations available. Each presentation has its own path in here, e.g., `/incubator/presentations/spindle` shows the spindle presentation

Currently, `https://incubator.c4dt.org/` (which would correspond to `https://factory.c4dt.org/incubator`) points to the list of projects, each having a small description and a link to the presentation. I am not clear on that the `/presentations` would show? Just  a list of links to the presentations?

**Comment by ineiti** [comment]
My proposition is to have the current `incubator.c4dt.org` in `/incubators`, and then filter this list according to presentations, demonstrators, hands-on, and pilots, then serve this filtered list in the `/incubators/(presentations|demos|hands-on|pilots)` pahts.

**Comment by cgrigis** [comment]
Ah OK, that make sense now.
Minor detail: I don't think it should be `incubators` though, to me it is "the" incubator (like there is "the" showcase"). which "incubates" the various projects.

**Comment by ineiti** [comment]
`s/incubators/incubator` - fixed in the description.

**Comment by cgrigis** [comment]
So if we are presenting filtered lists, `hands-on/` is the list filtered to show only the projects that have a hands-on, and `hands-on/{project}` points to its hands-on, doesn't it?

**Comment by tharvik** [comment]
I'm having an issue with the stability of informations over time. Let's say we have a partner interested in one of our incubating project, after a while, this project will enter the market, so IIUC, it will disapear from the incubator? Or it will stay in the incubator and be added to the market?
Put in another form, what is the stable address for a given project?

**Comment by ineiti** [comment]
Stability: the current proposition doesn't describe things as moving, rather as adding more information over time. The most stable link should be the factory.c4dt.org/showcase/project/SLAB/AICrowd - when all the others will be added, this first one will still be available.

The other stability with regard to the current URLs, we'll break it. I don't think there are many links around that people still use. But I should probably look at the logs to confirm that...

**Comment by tharvik** [comment]
> Stability: the current proposition doesn't describe things as moving, rather as adding more information over time.

All right, so I missunderstood, thanks for the clarification.

**Comment by cgrigis** [comment]
DNS: email support-icit@epfl.ch for:
`factory.c4dt.org. 300 IN CNAME srv1.c4dt.org.`

**Comment by ineiti** [comment]
> So if we are presenting filtered lists, `hands-on/` is the list filtered to show only the projects that have a hands-on, and `hands-on/{project}` points to its hands-on, doesn't it?

In fact I thought of not showing the actual documents and docker-files for the hands-on, but only a line like "If you are interested in one of the hands-on, please contact the Factory at linus.gasser@epfl.ch"

**Comment by cgrigis** [comment]
> So if we are presenting filtered lists, `hands-on/` is the list filtered to show only the projects that have a hands-on, and `hands-on/{project}` points to its hands-on, doesn't it?

We will not have specific pages for hands-on

**Comment by ineiti** [comment]
I'd like to give the users answers to the following questions:
- What is C4DT working on? _Factory > Incubator_
- What projects does Viktor have? _Factory > Showcase > Labs > LARA_
- What is in the showcase? _Factory > Showcase_
- What presentations are available? _Factory > Presentations_
- What is available for OmniLedger? _Factory > Showcase > Labs > DEDIS > OmniLedger_

Now jumping back and forth between these is not easy. Most specifically if you're in the `OmniLedger` presentation and would like to see what else is there for OmniLedger. There the breadcrumb doesn't have a direct access to this list.

**Comment by cgrigis** [comment]
Changes in #164 deployed to `factory.c4dt.org` on `c4dtsrv1`, to allow for comments/changes before merge
