### ISSUE TITLE
No link from presentation to demo

### ISSUE THREAD

**Issue by tharvik** [c4dt/showcase#170]
When seeing the presentation, one needs to go back the incubator page to access the demonstrator.
For example, https://factory.c4dt.org/incubator/spindle -> https://factory.c4dt.org/incubator -> https://factory.c4dt.org/incubator/spindle/demo.
I propose to add a link to the demo below the presentation.

**Comment by cgrigis** [comment]
Not directly related, but that reminds me: it is possible to use a `description:` field under `demo:`, whose contents is currently displayed on the main incubator page after the link to the demonstrator (see e.g. https://github.com/c4dt/showcase/blob/main/data/LARA/projects.yaml#L66-L86).

**Comment by ineiti** [comment]
> I propose to add a link to the demo below the presentation.

Definitely a good idea. The presentation should have links to the demo and pilot, if available.

**Comment by cgrigis** [comment]
Should we close this with #194?

**Comment by tharvik** [comment]
> Should we close this with #194?

Correct, it was duplicated.
