### ISSUE TITLE
Make sure links are found and available

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#179]
The current layout with showcase / incubator / demo is already much nicer than before. One issue that still need to be taken care of - feel free to add others:

1. how to go from the incubator back to the showcase? For example in incubator/omniledger, it would be nice to be able to go back to showcase/lab/DEDIS/omniledger
2. how to go from the showcase to the project page? For example https://factory.c4dt.org/showcase/labs/DCL/garfield doesn't point to https://factory.c4dt.org/incubator/garfield...

**Comment by cgrigis** [comment]
Isn't this the same as #170?

**Comment by ineiti** [comment]
I added a new issue in the hope that we find a nicer way than adding the links at the bottom of the presentation. So instead of putting it in the text of the presentation, I thought perhaps we can add something in the breadcrumbs themselves?

**Comment by ineiti** [comment]
Done in latest version of showcase
