### ISSUE TITLE
Selecting a lab from "All labs" sometimes yields surprising results

### ISSUE THREAD

**Issue by cgrigis** [c4dt/showcase#241]
When selecting a lab from the "All labs" drop-down, the resulting project list sometimes contains projects not related to that lab.

Examples: Laboratory for Data Security, Network Architecture Lab

**Comment by ineiti** [comment]
I didn't find a better way to do it with the available code for the table. But I might've missed something. In fact all the dropdowns are searches in the table...

**Comment by cgrigis** [comment]
Perhaps using the column search functions?
https://datatables.net/reference/api/column().search()
https://datatables.net/reference/api/columns().search()
