### ISSUE TITLE
sort dropdown menus

### ISSUE THREAD

**Issue by tharvik** [c4dt/showcase#271]
When opening the labs menu, the list isn't alphanumericaly sorted, making it bisect when reading it. It would be nice to be able to select it faster.

* for the project menu, it makes sense to keep the "[...] available" items together
* also, for menu w/ "Other" item, it should stay at the end of the list

**Comment by morganridel** [comment]
@ineiti Do we want to sort only the labs dropdown?
If not, should the sort also change the pillars grouping order in the table?
![image](https://user-images.githubusercontent.com/14032127/188846013-14e826cc-d20a-4881-9ed0-307d941612bf.png)

**Comment by tharvik** [comment]
> Do we want to sort only the labs dropdown? If not, should the sort also change the pillars grouping order in the table?

IMO, you can also order pillars and verticals, but keep the "Other" at the end
