### ISSUE TITLE
Update Maturity Evaluation

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#292]
Martin Jaggi requested a Maturity update for the 

https://factory.c4dt.org/showcase/powersgd/technical

Project.

**Comment by lanterno** [comment]
Evaluation is done and available [here](https://docs.google.com/spreadsheets/d/1rI1aQouS1WJSyZ2AvNUl9buPxbT0lr4qAWr7ezgt3lY/edit#gid=0)

There a couple of points, I would like to go over with you first @ineiti

**Comment by ineiti** [comment]
Things to write to Martin (write to me first, then I give feedback):
- congrats, it's a 2
- link to the spreadsheet, look at the notes
- happy to give more info
- Problem with link from https://pypi.org/project/powersgd/ to github

**Comment by ineiti** [comment]
Change showcase to use new maturity level.

**Comment by lanterno** [comment]
@ineiti I merged the the PR but [the page](https://factory.c4dt.org/showcase/powersgd/technical) wasn't updated. 

I'll type to Morgan on slack.
