### ISSUE TITLE
Updates needed

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#294]
Here some updates needed while going through the showcase:
- [ ] Update hydra with link to paper
  - https://factory.c4dt.org/showcase/hydra/technical
  - https://sanidhya.github.io/pubs/2019/hydra.pdf
- [ ] https://factory.c4dt.org/showcase/hbt/technical - Remove Noémien
- [x] https://factory.c4dt.org/showcase/{stainless,spindle,drynx}/demo points to non-existant service and should point to their github repos

**Comment by lanterno** [comment]
@ineiti  some questions:

Should I remove Noémien from all projects or just HBT? 

For Hydra, I also saw there's no link to the code so I added it, and also a link to the conference that the paper was published in. I'll let you review those information in the PR. 

For the last point in ticket description, should I look into that, or you already fixed those projects?

**Comment by ineiti** [comment]
> Should I remove Noémien from all projects or just HBT?

We should update the contact information for all projects, see #304. For this issue, just remove Noemien (he/him)

> For the last point in ticket description, should I look into that, or you already fixed those projects?

Done - I clicked the checkbox now.
