### ISSUE TITLE
Add 'type' to projects

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#307]
Each project should also have a 'type'. So go through the projects and choose between the available types.

**Comment by lanterno** [comment]
Most projects I'm looking at are specific application a new paper in a certain field. For example, a new method to improve Deep Learning on noisy images.  The github project then adds a way to reproduce the paper, but it doesn't put the project (in most cases) in a state where I can call it a "Library". 

In these cases, how should I think about the "type" of the project? 

I'm considering "Simulation" as some papers only publish code that reproduces / simulates their findings. 
I'm also considering "Application" in the sense that the code presents mostly a runnable script that applies some operations on data. 

@ineiti Can you give some insight on how I should make the choice?

**Comment by ineiti** [comment]
Created #314 (pi) with short comments - is this enough information?
