### ISSUE TITLE
Do a maturity evaluation

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#32]
Create a maturity evaluation of one of the projects in the showcase until 7th of February.

- [x] @ineiti
- [x] @cgrigis 
- [x] @tharvik

**Comment by cgrigis** [comment]
Evaluated Foolbox 2.0

**Comment by ineiti** [comment]
Merge showcase PR for FoolBox

**Comment by ineiti** [comment]
Mail Pascal for evaluation.

**Comment by tharvik** [comment]
Evaluated dedis/protobuf
