### ISSUE TITLE
Revamp showcase - Decide new framework

### ISSUE THREAD

**Issue by lanterno** [c4dt/showcase#329]
Before revamping the showcase, I went through it to:

- [x] Review the exist code and determine the different components
- [x] Analyze those components to determine their requirements (for the desired revamp)
- [x] Propose two alternative programing frameworks for the implementation
- [x] Discuss with team and either add new alternatives or choose one -> go with VueJS

**Comment by lanterno** [comment]
# Existing system components:

- **data:** as YAML objects in directory-based tree structure
    - Depends on a schema library “strictyaml”. This library is also used to validate the existing data. (1)
- Data module: responsible for loading the data from its YAML files to python formats.
- **History of changes** (6 changes)
- server: 100 lines
- Custom data presentation structure
    - Some data require special display so it was included in special files that contained both data and UI design. This is going to be the most difficult to migrate (into a cleaner format)
- Tests: very simplistic tests (very easy to migrate)
    - runs on **GitHub CI**
    - The only important test is one that imports all data and applies the schema model for validation.

---

# System analysis:

- Existing data system is simple on purpose to keep the app serverless
- Changes history might be better to be migrated to GitHub releases (or maintained by  a changelog tool)
- the only goal of the server is
    - page routing
    - serving static data
- Custom data presentation:
    - Complex to standardize
    - Or could use a CMS (over engineering?)
- Data loader: other languages might maintain even better libraries for schema validation.
    - Should we use OpenAPI for model validation? Is there better alternatives?
        - Maybe something like pydantic?

---

# Proposal #1

Typescript/ VueJs/ Nuxt combination 

Why? 

- No need for a server:
    - Works well with static data
    - page routing is done on the frontend
    - Good tools for schema validation
- Can be compiled on the CI and deployed as a static site (maybe on GitHub pages)

Why not?

- Learning curve and configuration

# Proposal #2

Hugo!

Why?

- Targets static sites
    - easier - faster - no learning curve
- Easy to migrate to it from python templating
- Nice themes out of the box
- Based on Go (a good opportunity to practice it?)

Why not?

- Is it easy to add the data loader?
- Is it easy to add tests?

Hugo investigation:

- Very Flexible
- Won’t support data validation. We can keep it in Python.
    - Or port it to go (to maintain only a single language per project)
- Supports YAML files to import the projects.

**Comment by lanterno** [comment]
# System analysis:

- Existing data system is simple on purpose to keep the app serverless
- Changes history might be better to be migrated to GitHub releases (or maintained by  a changelog tool)
- the only goal of the server is
    - page routing
    - serving static data
- Custom data presentation:
    - Complex to standardize
    - Or could use a CMS (over engineering?)
- Data loader: other languages might maintain even better libraries for schema validation.
    - Should we use OpenAPI for model validation? Is there better alternatives?
        - Maybe something like pydantic?

**Comment by ineiti** [comment]
Let's go with VueJS
