### ISSUE TITLE
Revamp Showcase

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#330]
- [x] Search for other implementations of such lists and present them
  - which other lists exist to present projects?
  - what are the pros and the cons for these lists?
  - what can we learn from them?
- [x] Start implementing a demo w/o all the functionalities
  - once we decided on which list to implement
  - create a mock of the list

**Comment by lanterno** [comment]
Classic approach: 
- https://opensourcesecurityindex.io/

Modern approach:
- https://depinhub.io/projects

**Comment by lanterno** [comment]
Here's the best choices showing different styles:

 - https://cltc.berkeley.edu/research/research-library/
 - https://dev.near.org/applications
 - https://lido.fi/lido-ecosystem
 - https://www.uniswapfoundation.org/funded-grants
 - https://grants.gitcoin.co/
 - https://blockworks.co/grants

**Comment by lanterno** [comment]
The different sites cater to different types of users

### Project managers
Appreciate a minimal style that would focus on the important most successful projects first, delve the different use cases, and show a list of all projects under each category.

### Developers
Appreciate strong filters with focus on 1.obvious important information (dates, usage stats) 2.the nitty-gritty details for each project.

Assuming we want to appeal to both types of users, we need a mix of both styles. We start with a selected number of projects we strongly support, then follow with a full list with good filters 
We use something similar to https://thegraph.com/ecosystem/grants/ 

and we then follow with either
1. https://depinhub.io/projects
2. https://blockworks.co/grants
3. https://cltc.berkeley.edu/research/research-library/

**Comment by lanterno** [comment]
Good requirements:
- It should show the maturity (popularity) of the project. 
- If the project is in use (more than the last commit date?)
- Put a direct link to github on the list
- Show a previous of the description on the table page

An idea:
Start with selected projects section (targeted towards journalists, Management-level people, etc)
Then follow with a more modern-looking table 

Extras:
- Pull the last commit date from github

Who are the potential user:
- Managers: What projects does C4DT has to offer my company?
- Journalists: They're only interested in C4DT.org or EPFL site.
- Researchers of the partner companies: What is interesting in coming years?
     - Is there any libraries for the topic I'm working on right now?
- Researchers of other institutions: 
    - What are Digital Trust labs at EPFL working on right now?
    - What are the works at EPFL that are relevant to my research topic?

**Comment by ineiti** [comment]
LGTM - implement it :)

I'd also want a condensed view if that is possible to have a bigger overview of the parts.

**Comment by lanterno** [comment]
@PascalinDe and I to discuss actual tasks and planning today after the weekly meeting.

**Comment by lanterno** [comment]
Following work moved to https://github.com/c4dt/showcase_v2/issues/2
