### ISSUE TITLE
Active / Inactive

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#46]
Suggestion: add a color to the projects depending on whether they're active or not.

Active: green
Inactive / no info: keep gray

Eventually also sort to have active projects on top, and inactive projects at the bottom.

**Comment by cgrigis** [comment]
What I have done so far:
* The "project name" cell is colored green if the project is active (in two colors, depending on row number parity, as is done for the grey).
* The default sort is on Professor name, as before.
* If you sort by project name, the active ones come first (the greens are slightly darker, as is the case for the greys on a sorted column).

What do you think?

You can play with it by checking out the `activity-improvements` branch, typing `make` and browsing to `http://0.0.0.0:8080/`.

**Comment by ineiti** [comment]
I like it. What I'd change (but we should really ask David for 5 minutes ;):
- make the green less green (just increase 10% compared to Red and Blue)
- highlight the whole line
- use the same green in all sorting modes

**Comment by cgrigis** [comment]
I applied those changes. Also set the default sort to be "Professor name" + "Project name".

**Comment by ineiti** [comment]
As written in the comment to #69 , I prefer having the sort start with active projects. The most common use-case is people looking for active projects!

**Comment by cgrigis** [comment]
> As written in the comment to #69 , I prefer having the sort start with active projects. The most common use-case is people looking for active projects!

Ah, it wasn't clear to me: right now, the default sort is by lab first, and then within a lab by project, with the active ones first. You would like the sort to be on projects only, independently of the lab/professor?

**Comment by ineiti** [comment]
My favourite would be to sort by active/inactive, then lab/professor.
