### ISSUE TITLE
Better explain maturity

### ISSUE THREAD

**Issue by ineiti** [c4dt/showcase#78]
Some ideas to better explain the maturity column:

- mouse-over
- link with explanations
- text above that says what it means
- remove the moon for maturity == 0

**Comment by cgrigis** [comment]
I added a tooltip over the image that shows the text label of the maturity, i.e. "Not yet assessed", "Prototype", "Intermediate" or "Mature".
Should we perhaps add a link at the top of the page to the Google Doc document that describes the maturity evaluation process, as well as how the level is reached?
